# Demo to test and show the functionality of the library

In [1]:
# Importing Functions
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('TKAgg') # Needed to have figures display properly. 
import flirimageextractor
import Utils as u
import cv2

DEBUG=False

In [2]:
#filename = "C:\\Users\\Francisco\\Documents\\dataset_termal_destino\\Control_Image termal C_paciente 3 (VC)_flir_control_flir_20190907T092339.jpg"
#filename = "C:\\Users\\Francisco\\Documents\\ThermalDataset\\Control\\Thermal-Images\\paciente_3\\flir\\control\\flir_20190907T092339.jpg"
filename = "C:\\Users\\Francisco\\Documents\\ThermalDataset\\Control\\Thermal-Images\\paciente_4\\flir\\control\\flir_20190907T104934.jpg"
#filename = "D:\\FLIROne\FLIR_20230426_044637_061.jpg"
#filename = "D:\\FLIROne\FLIR_20230426_044706_939.jpg"
flir = flirimageextractor.FlirImageExtractor(exiftool_path="C:\\Windows\\exiftool.exe")
flir.process_image(filename, RGB=True)

In [3]:
therm = flir.get_thermal_np()
rgb_fullres = flir.get_rgb_np()
if DEBUG:
    plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.imshow(therm)
    plt.title('Raw Thermal Image')
    plt.subplot(1,2,2)
    plt.imshow(rgb_fullres)
    plt.title('RGB Full Resolution Image')
    plt.show(block='TRUE') 

In [4]:
colormap_image, Imsalida,temp_img_resized,image_copy = u.extract_images(flir,plot=0)

In [5]:
#u.save_thermal_csv(temp_img_resized,"temperature_examples.csv",delimiter=";")

# second part of the demo get the perspective transformation between two images

In [6]:
#filename2 = "C:\\Users\\Francisco\\Documents\\dataset_termal_destino\\Control_Image termal C_paciente 3 (VC)_flir_control_flir_20190907T092409.jpg"
#filename2 = "C:\\Users\\Francisco\\Documents\\ThermalDataset\\Control\\Thermal-Images\\paciente_3\\flir\\control\\flir_20190907T093339.jpg"
filename2 = "C:\\Users\\Francisco\\Documents\\ThermalDataset\\Control\\Thermal-Images\\paciente_4\\flir\\control\\flir_20190907T105015.jpg"
flir2 = flirimageextractor.FlirImageExtractor(exiftool_path="C:\\Windows\\exiftool.exe")
flir2.process_image(filename2, RGB=True)
therm2 = flir2.get_thermal_np()
rgb_fullres2 = flir2.get_rgb_np()
colormap_image2, Imsalida2,temp_img_resized2,image_copy2 = u.extract_images(flir2,plot=0)
#u.save_thermal_csv(temp_img_resized2,"temperature_examples2.csv",delimiter=";")
if DEBUG:
    plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.imshow(temp_img_resized2)
    plt.title('temp_img_resized2')
    plt.subplot(1,2,2)
    plt.imshow(image_copy2)
    plt.title('image_copy2')
    plt.show(block='TRUE') 


In [7]:


"""
def fethearing_bin_to_color(binary_image, color_image):
    # Operación de cierre morfológico con un kernel elíptico de tamaño 5x5
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))
    closed_image = cv2.morphologyEx(binary_image, cv2.MORPH_CLOSE, kernel)
    
    # Fethearing usando filtro guiado
    filtered_image = cv2.ximgproc.guidedFilter(color_image, closed_image, 20, eps=0.1)#5, eps=1e-4
    
    # Umbralización de la imagen filtrada
    _, thresholded_image = cv2.threshold(filtered_image,20, 255, cv2.THRESH_BINARY)
    
    return filtered_image
"""


'\ndef fethearing_bin_to_color(binary_image, color_image):\n    # Operación de cierre morfológico con un kernel elíptico de tamaño 5x5\n    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))\n    closed_image = cv2.morphologyEx(binary_image, cv2.MORPH_CLOSE, kernel)\n    \n    # Fethearing usando filtro guiado\n    filtered_image = cv2.ximgproc.guidedFilter(color_image, closed_image, 20, eps=0.1)#5, eps=1e-4\n    \n    # Umbralización de la imagen filtrada\n    _, thresholded_image = cv2.threshold(filtered_image,20, 255, cv2.THRESH_BINARY)\n    \n    return filtered_image\n'

In [8]:
import registration_simpleitk as sr

In [9]:

segmented_Feet,segmented_temps=u.Find_feets(image_copy,temp_img_resized,percentage=20)
if DEBUG:
    u.plot_images_and_thermal(segmented_Feet,segmented_temps)
segmented_Feet2,segmented_temps2=u.Find_feets(image_copy2,temp_img_resized2,percentage=20)
print(segmented_Feet2[1].shape)
if DEBUG:
    u.plot_images_and_thermal(segmented_Feet2,segmented_temps2)

(525, 224, 3)


In [10]:
#u.visualize_descriptors(segmented_Feet[0],segmented_Feet2[0])
#u.visualize_descriptors(segmented_Feet[1],segmented_Feet2[1])

"""
output_image,homography_matrix=u.matchbydescriptors(segmented_Feet[0],segmented_Feet2[0])
plt.figure(figsize=(10,5))
plt.imshow(output_image)
plt.title('registration between images')
plt.show(block='TRUE') 

output_image,homography_matrix=u.matchbydescriptors(segmented_Feet[1],segmented_Feet2[1])
plt.figure(figsize=(10,5))
plt.imshow(output_image)
plt.title('registration between images')
plt.show(block='TRUE') 
"""

"\noutput_image,homography_matrix=u.matchbydescriptors(segmented_Feet[0],segmented_Feet2[0])\nplt.figure(figsize=(10,5))\nplt.imshow(output_image)\nplt.title('registration between images')\nplt.show(block='TRUE') \n\noutput_image,homography_matrix=u.matchbydescriptors(segmented_Feet[1],segmented_Feet2[1])\nplt.figure(figsize=(10,5))\nplt.imshow(output_image)\nplt.title('registration between images')\nplt.show(block='TRUE') \n"

In [11]:
# using a different approach
"""
registered_image_a_array, registered_image_b_array, composition_image =sr.register_images(segmented_Feet[0],segmented_Feet2[0],'displaceMeth4.hdf5')
if DEBUG:
    plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.imshow(registered_image_a_array)
    plt.title('registered_image_a_array')
    plt.subplot(1,2,2)
    plt.imshow(registered_image_b_array)
    plt.title('registered_image_b_array')
    plt.show(block='TRUE') 
    
plt.figure(figsize=(10,5))
plt.imshow(composition_image)
plt.title('composition_image')
plt.show(block='TRUE') 
"""

"\nregistered_image_a_array, registered_image_b_array, composition_image =sr.register_images(segmented_Feet[0],segmented_Feet2[0],'displaceMeth4.hdf5')\nif DEBUG:\n    plt.figure(figsize=(10,5))\n    plt.subplot(1,2,1)\n    plt.imshow(registered_image_a_array)\n    plt.title('registered_image_a_array')\n    plt.subplot(1,2,2)\n    plt.imshow(registered_image_b_array)\n    plt.title('registered_image_b_array')\n    plt.show(block='TRUE') \n    \nplt.figure(figsize=(10,5))\nplt.imshow(composition_image)\nplt.title('composition_image')\nplt.show(block='TRUE') \n"

In [12]:
# using a different approach
output =sr.register_images_Similarity2DTransform(segmented_Feet[0],segmented_Feet2[0],'displaceMeth4_advanced.hdf5')
fixed_imagen = sr.sitk_image_to_opencv(output["fixed"])
moving_imagen = sr.sitk_image_to_opencv(output["moving"])
composition_image = sr.sitk_image_to_opencv(output["composition"])
if DEBUG:
    plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.imshow(fixed_imagen)
    plt.title('fixed_imagen')
    plt.subplot(1,2,2)
    plt.imshow(moving_imagen)
    plt.title('moving_imagen')
    plt.show(block='TRUE') 

plt.figure(figsize=(10,5))
plt.imshow(composition_image)
plt.title('composition_image')
plt.show(block='TRUE') 

thermalout= sr.cv2_grid_sampling(segmented_temps[0], segmented_temps2[0], output["Transform"], is_binary=False)

plt.figure(figsize=(10,5))
plt.imshow(thermalout)
plt.title('thermalout')
plt.show(block='TRUE') 



  0 =   -1.18686 : (0.9999722353940698, 0.00015811403669645647, 2.493677342749642, -1.40020020924685)
  1 =   -1.19050 : (0.9999554348828051, 0.0003226375786312676, 2.4842832107211663, -1.3006425730094495)
  2 =   -1.19413 : (0.9999447750627003, 0.000493366396953364, 2.472229808969731, -1.201371800652943)
  3 =   -1.19757 : (0.9999637794398273, 0.0006896991876526421, 2.459181259997695, -1.1022269749584404)
  4 =   -1.20075 : (1.0000053381548868, 0.0009089527862670447, 2.4444285619901684, -1.0033214235357248)
  5 =   -1.20355 : (1.0000139626341327, 0.0011087118139974377, 2.425464887178348, -0.9051361952191358)
  6 =   -1.20720 : (0.9999894559946281, 0.0012924532036469598, 2.4071760761942937, -0.8068229965563118)
  7 =   -1.21180 : (0.9999611195659004, 0.0014748419619995748, 2.3871996260038806, -0.7088387765554485)
  8 =   -1.21548 : (0.9999663355230651, 0.0016773742107753053, 2.3624424891302045, -0.6119520224179501)
  9 =   -1.21818 : (1.0000174935065065, 0.0019140935075456092, 2.334958

 35 =   -1.27341 : (1.0029965554023041, 0.011998127367739708, 0.9897688769977038, 0.8325129339009042)
 36 =   -1.27345 : (1.0029733428898606, 0.012012707332022265, 0.9791810683808085, 0.8391572967218154)
 37 =   -1.27347 : (1.0029489699824496, 0.012076097635997029, 0.9675730632780636, 0.8437940633932571)
 38 =   -1.27346 : (1.0029597189386996, 0.012120714365589081, 0.9681120647960256, 0.8375675177079662)
 39 =   -1.27343 : (1.0029548887041912, 0.012131972420027394, 0.9650553494961894, 0.8382171071943285)
 40 =   -1.27342 : (1.0029504786144554, 0.01215149257572395, 0.9619308599820686, 0.8381642887242694)
 41 =   -1.27341 : (1.0029470859525251, 0.012179482561203743, 0.9589778876074252, 0.8371421418634171)
 42 =   -1.27339 : (1.0029434475977916, 0.012205147209575641, 0.9559941801820322, 0.8362134637233419)
 43 =   -1.27337 : (1.0029396659559433, 0.01223217799543316, 0.9530751825849832, 0.8350979669442237)
 44 =   -1.27336 : (1.0029340382545673, 0.012253562682982794, 0.9499635719519891, 0.

In [13]:

print(type(fixed_imagen))

print(fixed_imagen.shape)

print(fixed_imagen)

<class 'numpy.ndarray'>
(539, 236)
[[24 24 23 ... 33 34 34]
 [23 23 24 ... 34 34 34]
 [24 23 24 ... 34 34 34]
 ...
 [10 10  9 ... 16 16 16]
 [10 10 10 ... 16 16 16]
 [10 11 10 ... 16 16 16]]
